name: TheIntegralEducator
favicon: null
layout_spectrum: 0.17151184612885118
typography_spectrum: 0.5690118588972837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12158737028948963
  lightness: 0.2805764207150787
  saturation: 0.5907294801436365
  rhythmicContrast: 0.9167299678083509
purpose: []
