typography_spectrum: 0.5690118588972837
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12158737028948963
  lightness: 0.2805764207150787
  saturation: 0.5907294801436365
  rhythmicContrast: 0.9167299678083509
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.17151184612885118
analytics:
  google: null
  facebook: null
  twitter: null
name: TheIntegralEducator
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Posts
    id: 01494cf1-7158-4472-8ad6-b0fbac5911f0
    type: content
  - name: Setting a foundation of mindfulness in your classroom
    id: 3e98d576-30bc-46d6-8b19-47841abeef30
    type: content
favicon: null
title: 'For educators working for a more loving, just, and sustainable world.'
description: School's in!
purpose: []
